version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/NaturalLanguageTimespanParser"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"